/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantbd;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author enriq
 */
public class frmJuzgados extends javax.swing.JFrame {

    private Bd bd = new Bd();
    List<altaExpedientes> listaExpedientes;
   
    int idIngredienteModificar;

    /**
     * Creates new form frmABC
     */
    public frmJuzgados() {

        initComponents();
        setLocationRelativeTo(null);
        cargarDatosExpedientes();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        menuPrincipal = new javax.swing.JTabbedPane();
        pnlExpedientes = new javax.swing.JPanel();
        pnlExpedientesABC = new javax.swing.JPanel();
        pnlAgregarModificarExpediente = new javax.swing.JPanel();
        lblFechaExpediente = new javax.swing.JLabel();
        txtFecha = new javax.swing.JTextField();
        lblTipoCaso = new javax.swing.JLabel();
        txtTipoCaso = new javax.swing.JTextField();
        pnlBotonesABCExpedientes = new javax.swing.JPanel();
        btnActualizarExpediente = new javax.swing.JButton();
        btnAgregarExpediente = new javax.swing.JButton();
        btnEliminarExpediente = new javax.swing.JButton();
        btnLimpiarExpedientes = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        pnlTablaIngredientes = new javax.swing.JPanel();
        scrollPaneIngredientes = new javax.swing.JScrollPane();
        tblABCExpedientes = new javax.swing.JTable();
        pnlAdministradores = new javax.swing.JPanel();
        pnlAdministradoresABC = new javax.swing.JPanel();
        pnlAgregarModificarAdministrador = new javax.swing.JPanel();
        lblNombreAdministrador = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        lblContrasñaPWD = new javax.swing.JLabel();
        pswContraseña = new javax.swing.JPasswordField();
        pnlBotonesABCExpedientes1 = new javax.swing.JPanel();
        btnActualizarAdministrador = new javax.swing.JButton();
        btnAgregarAdministrador = new javax.swing.JButton();
        btnEliminarAdministrador = new javax.swing.JButton();
        btnLimpiarAdministradors = new javax.swing.JButton();
        lblLogo1 = new javax.swing.JLabel();
        pnlTablaIngredientes1 = new javax.swing.JPanel();
        scrollPaneIngredientes1 = new javax.swing.JScrollPane();
        tblABCExpedientes1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPrincipal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        menuPrincipal.setFont(new java.awt.Font("Franklin Gothic Book", 0, 14)); // NOI18N

        pnlExpedientesABC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EXPEDIENTES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 24))); // NOI18N

        pnlAgregarModificarExpediente.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Manejo de Expedientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        lblFechaExpediente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblFechaExpediente.setText("Fecha");

        lblTipoCaso.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblTipoCaso.setText("Tipo");

        txtTipoCaso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTipoCasoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAgregarModificarExpedienteLayout = new javax.swing.GroupLayout(pnlAgregarModificarExpediente);
        pnlAgregarModificarExpediente.setLayout(pnlAgregarModificarExpedienteLayout);
        pnlAgregarModificarExpedienteLayout.setHorizontalGroup(
            pnlAgregarModificarExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarModificarExpedienteLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlAgregarModificarExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaExpediente)
                    .addGroup(pnlAgregarModificarExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(pnlAgregarModificarExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoCaso)
                            .addGroup(pnlAgregarModificarExpedienteLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(txtTipoCaso, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(451, Short.MAX_VALUE))
        );
        pnlAgregarModificarExpedienteLayout.setVerticalGroup(
            pnlAgregarModificarExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarModificarExpedienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAgregarModificarExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFechaExpediente)
                    .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAgregarModificarExpedienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipoCaso)
                    .addComponent(txtTipoCaso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );

        btnActualizarExpediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bdAct.png"))); // NOI18N
        btnActualizarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarExpedienteActionPerformed(evt);
            }
        });

        btnAgregarExpediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bdAdd1.png"))); // NOI18N
        btnAgregarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarExpedienteActionPerformed(evt);
            }
        });

        btnEliminarExpediente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bdErase.png"))); // NOI18N
        btnEliminarExpediente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarExpedienteActionPerformed(evt);
            }
        });

        btnLimpiarExpedientes.setText("Limpiar");
        btnLimpiarExpedientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarExpedientesActionPerformed(evt);
            }
        });

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logoEscudo.png"))); // NOI18N

        javax.swing.GroupLayout pnlBotonesABCExpedientesLayout = new javax.swing.GroupLayout(pnlBotonesABCExpedientes);
        pnlBotonesABCExpedientes.setLayout(pnlBotonesABCExpedientesLayout);
        pnlBotonesABCExpedientesLayout.setHorizontalGroup(
            pnlBotonesABCExpedientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesABCExpedientesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnActualizarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarExpedientes)
                .addGap(18, 18, 18)
                .addComponent(lblLogo))
        );
        pnlBotonesABCExpedientesLayout.setVerticalGroup(
            pnlBotonesABCExpedientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesABCExpedientesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesABCExpedientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarExpediente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarExpediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarExpediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lblLogo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBotonesABCExpedientesLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnLimpiarExpedientes)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblABCExpedientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Fecha", "Tipo", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblABCExpedientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblABCExpedientesMouseClicked(evt);
            }
        });
        scrollPaneIngredientes.setViewportView(tblABCExpedientes);
        if (tblABCExpedientes.getColumnModel().getColumnCount() > 0) {
            tblABCExpedientes.getColumnModel().getColumn(1).setHeaderValue("Fecha");
            tblABCExpedientes.getColumnModel().getColumn(2).setHeaderValue("Tipo");
        }

        javax.swing.GroupLayout pnlTablaIngredientesLayout = new javax.swing.GroupLayout(pnlTablaIngredientes);
        pnlTablaIngredientes.setLayout(pnlTablaIngredientesLayout);
        pnlTablaIngredientesLayout.setHorizontalGroup(
            pnlTablaIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaIngredientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE))
        );
        pnlTablaIngredientesLayout.setVerticalGroup(
            pnlTablaIngredientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaIngredientesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPaneIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout pnlExpedientesABCLayout = new javax.swing.GroupLayout(pnlExpedientesABC);
        pnlExpedientesABC.setLayout(pnlExpedientesABCLayout);
        pnlExpedientesABCLayout.setHorizontalGroup(
            pnlExpedientesABCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExpedientesABCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlExpedientesABCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotonesABCExpedientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAgregarModificarExpediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTablaIngredientes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlExpedientesABCLayout.setVerticalGroup(
            pnlExpedientesABCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlExpedientesABCLayout.createSequentialGroup()
                .addComponent(pnlBotonesABCExpedientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAgregarModificarExpediente, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlTablaIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlExpedientesLayout = new javax.swing.GroupLayout(pnlExpedientes);
        pnlExpedientes.setLayout(pnlExpedientesLayout);
        pnlExpedientesLayout.setHorizontalGroup(
            pnlExpedientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlExpedientesABC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlExpedientesLayout.setVerticalGroup(
            pnlExpedientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExpedientesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlExpedientesABC, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPrincipal.addTab("ABC Expedientes", pnlExpedientes);

        pnlAdministradoresABC.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "EXPEDIENTES", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Consolas", 0, 24))); // NOI18N

        pnlAgregarModificarAdministrador.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Manejo de Expedientes", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 14))); // NOI18N

        lblNombreAdministrador.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblNombreAdministrador.setText("Usuario");

        lblContrasñaPWD.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        lblContrasñaPWD.setText("Contraseña");

        javax.swing.GroupLayout pnlAgregarModificarAdministradorLayout = new javax.swing.GroupLayout(pnlAgregarModificarAdministrador);
        pnlAgregarModificarAdministrador.setLayout(pnlAgregarModificarAdministradorLayout);
        pnlAgregarModificarAdministradorLayout.setHorizontalGroup(
            pnlAgregarModificarAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarModificarAdministradorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(pnlAgregarModificarAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContrasñaPWD)
                    .addComponent(lblNombreAdministrador))
                .addGap(18, 18, 18)
                .addGroup(pnlAgregarModificarAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pswContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAgregarModificarAdministradorLayout.setVerticalGroup(
            pnlAgregarModificarAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAgregarModificarAdministradorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlAgregarModificarAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreAdministrador)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAgregarModificarAdministradorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrasñaPWD)
                    .addComponent(pswContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(101, 101, 101))
        );

        btnActualizarAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bdAct.png"))); // NOI18N
        btnActualizarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarAdministradorActionPerformed(evt);
            }
        });

        btnAgregarAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bdAdd1.png"))); // NOI18N
        btnAgregarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarAdministradorActionPerformed(evt);
            }
        });

        btnEliminarAdministrador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bdErase.png"))); // NOI18N
        btnEliminarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAdministradorActionPerformed(evt);
            }
        });

        btnLimpiarAdministradors.setText("Limpiar");
        btnLimpiarAdministradors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarAdministradorsActionPerformed(evt);
            }
        });

        lblLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/logoEscudo.png"))); // NOI18N

        javax.swing.GroupLayout pnlBotonesABCExpedientes1Layout = new javax.swing.GroupLayout(pnlBotonesABCExpedientes1);
        pnlBotonesABCExpedientes1.setLayout(pnlBotonesABCExpedientes1Layout);
        pnlBotonesABCExpedientes1Layout.setHorizontalGroup(
            pnlBotonesABCExpedientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesABCExpedientes1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnActualizarAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAgregarAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEliminarAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnLimpiarAdministradors)
                .addGap(18, 18, 18)
                .addComponent(lblLogo1))
        );
        pnlBotonesABCExpedientes1Layout.setVerticalGroup(
            pnlBotonesABCExpedientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBotonesABCExpedientes1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBotonesABCExpedientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnEliminarAdministrador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregarAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnActualizarAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(lblLogo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBotonesABCExpedientes1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(btnLimpiarAdministradors)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblABCExpedientes1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Usuario", "Contraseña"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblABCExpedientes1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblABCExpedientes1MouseClicked(evt);
            }
        });
        scrollPaneIngredientes1.setViewportView(tblABCExpedientes1);

        javax.swing.GroupLayout pnlTablaIngredientes1Layout = new javax.swing.GroupLayout(pnlTablaIngredientes1);
        pnlTablaIngredientes1.setLayout(pnlTablaIngredientes1Layout);
        pnlTablaIngredientes1Layout.setHorizontalGroup(
            pnlTablaIngredientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTablaIngredientes1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPaneIngredientes1, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE))
        );
        pnlTablaIngredientes1Layout.setVerticalGroup(
            pnlTablaIngredientes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlTablaIngredientes1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(scrollPaneIngredientes1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout pnlAdministradoresABCLayout = new javax.swing.GroupLayout(pnlAdministradoresABC);
        pnlAdministradoresABC.setLayout(pnlAdministradoresABCLayout);
        pnlAdministradoresABCLayout.setHorizontalGroup(
            pnlAdministradoresABCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdministradoresABCLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdministradoresABCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlBotonesABCExpedientes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlAgregarModificarAdministrador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlTablaIngredientes1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        pnlAdministradoresABCLayout.setVerticalGroup(
            pnlAdministradoresABCLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdministradoresABCLayout.createSequentialGroup()
                .addComponent(pnlBotonesABCExpedientes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlAgregarModificarAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlTablaIngredientes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlAdministradoresLayout = new javax.swing.GroupLayout(pnlAdministradores);
        pnlAdministradores.setLayout(pnlAdministradoresLayout);
        pnlAdministradoresLayout.setHorizontalGroup(
            pnlAdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdministradoresABC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnlAdministradoresLayout.setVerticalGroup(
            pnlAdministradoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdministradoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAdministradoresABC, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuPrincipal.addTab("ABC Expedientes", pnlAdministradores);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(menuPrincipal))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 643, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void tblABCExpedientesMouseClicked(java.awt.event.MouseEvent evt) {                                               
//        /*
//        Se almacena en una variable, la fila seleccionada dentro de la tabla.
//         */
//        int fila = tblABCExpedientes.getSelectedRow();
//        /*
//        Se obtienen los datos de la fila seleccionada.
//         */
//        if (fila >= 0) {
//            txtNombreIngrediente.setText(tblABCExpedientes.getValueAt(fila, 0).toString());
//            /*
//            Se coloca el nombre de la clase que guardara los datos recibidos.
//             */
//            for (altaIngredientes ingredientes : listaIngredientes) {
//                if (ingredientes.getNombre().equals(txtNombreIngrediente.getText())) {
//                    idIngredienteModificar = ingredientes.getClaveIngrediente();
//
//                }
//            }
//            /*
//            Se obtienen los datos de la fila seleccionada y son llenados dentro de los campos de texto.
//             */
//
//            txtNombreIngrediente.setText(tblABCExpedientes.getValueAt(fila, 0).toString());
//            txtFecha.setText(tblABCExpedientes.getValueAt(fila, 1).toString());
//            txtTipoCaso.setText(tblABCExpedientes.getValueAt(fila, 2).toString());
//
//            /*
//            Se manda mensaje de error en caso que exista alguno.
//             */
//        } else {
//            JOptionPane.showMessageDialog(null, "No se Selecciono nada");
//        }
    }                                              

    private void btnLimpiarExpedientesActionPerformed(java.awt.event.ActionEvent evt) {                                                      
        /*
        Limpia los campos de todo tipo de texto, al ser ejecutada esta acción.
         */
        tblABCExpedientes.clearSelection();
        txtFecha.setText("");
        txtTipoCaso.setText("");

    }                                                     

    private void btnEliminarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {                                                      
//
//        eliminarIngrediente();
//        /*
//        Se manda llamar el método con este nombre.
//         */
    }                                                     

    private void btnAgregarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {                                                     
      //  agregarIngrediente();
    }                                                    

    private void btnActualizarExpedienteActionPerformed(java.awt.event.ActionEvent evt) {                                                        
//        modificarIngrediente();

        /*
        Se manda llamar el método con este nombre.
         */
    }                                                       

    private void txtTipoCasoActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void btnActualizarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {                                                           
        // TODO add your handling code here:
    }                                                          

    private void btnAgregarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {                                                        
        // TODO add your handling code here:
    }                                                       

    private void btnEliminarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void btnLimpiarAdministradorsActionPerformed(java.awt.event.ActionEvent evt) {                                                         
        // TODO add your handling code here:
    }                                                        

    private void tblABCExpedientes1MouseClicked(java.awt.event.MouseEvent evt) {                                                
        // TODO add your handling code here:
    }                                               

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJuzgados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJuzgados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJuzgados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJuzgados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJuzgados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnActualizarAdministrador;
    private javax.swing.JButton btnActualizarExpediente;
    private javax.swing.JButton btnAgregarAdministrador;
    private javax.swing.JButton btnAgregarExpediente;
    private javax.swing.JButton btnEliminarAdministrador;
    private javax.swing.JButton btnEliminarExpediente;
    private javax.swing.JButton btnLimpiarAdministradors;
    private javax.swing.JButton btnLimpiarExpedientes;
    private javax.swing.JLabel lblContrasñaPWD;
    private javax.swing.JLabel lblFechaExpediente;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblLogo1;
    private javax.swing.JLabel lblNombreAdministrador;
    private javax.swing.JLabel lblTipoCaso;
    private javax.swing.JTabbedPane menuPrincipal;
    private javax.swing.JPanel pnlAdministradores;
    private javax.swing.JPanel pnlAdministradoresABC;
    private javax.swing.JPanel pnlAgregarModificarAdministrador;
    private javax.swing.JPanel pnlAgregarModificarExpediente;
    private javax.swing.JPanel pnlBotonesABCExpedientes;
    private javax.swing.JPanel pnlBotonesABCExpedientes1;
    private javax.swing.JPanel pnlExpedientes;
    private javax.swing.JPanel pnlExpedientesABC;
    private javax.swing.JPanel pnlTablaIngredientes;
    private javax.swing.JPanel pnlTablaIngredientes1;
    private javax.swing.JPasswordField pswContraseña;
    private javax.swing.JScrollPane scrollPaneIngredientes;
    private javax.swing.JScrollPane scrollPaneIngredientes1;
    private javax.swing.JTable tblABCExpedientes;
    private javax.swing.JTable tblABCExpedientes1;
    private javax.swing.JTextField txtFecha;
    private javax.swing.JTextField txtTipoCaso;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration                   

    private void cargarDatosExpedientes() {
        listaExpedientes = bd.getExpedientes();
        /*
         Se crea un modelo para ser insertado en una tabla del formulario principal.  
         */
        DefaultTableModel modelo = (DefaultTableModel) tblABCExpedientes.getModel();
        /*
         Acorde a los datos recibidos,  son enviados para ser insertados dentro de su tabla correspondiente.  
         */
        modelo.setRowCount(0);
        for (altaExpedientes expedientes : listaExpedientes) {
            modelo.addRow(
                    new Object[]{
                        
                        expedientes.getClaveExpediente(),
                        expedientes.getFecha(),
                        expedientes.getTipo(),
                        expedientes.getEstado()
                        

                    }
            );
        }

    }

   

//    private void eliminarIngrediente() {
//
//        /*
//         Se crea un modelo para ser insertado en una tabla del formulario principal.  
//         */
//        DefaultTableModel modelo = (DefaultTableModel) tblABCExpedientes.getModel();
//
//        int respuesta;
//        /*
//         Se verifica si se ha seleccionado la fila, dentro de la tabla antes de enviar los datos correspondientes a la fila.  
//         */
//        if (tblABCExpedientes.getSelectedRowCount() == 1) {
//            respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar el registro seleccionado?");
//        } else if (tblABCExpedientes.getSelectedRowCount() == 0) {
//            return;
//        } else {
//            respuesta = JOptionPane.showConfirmDialog(this, "¿Estás seguro de eliminar los " + tblABCExpedientes.getSelectedRowCount() + " registros seleccionados?");
//        }
//        /*
//         Si la respuesta dada por el usuario, coincide con la opción, se ejecutan el codigo.  
//         */
//        if (respuesta == JOptionPane.YES_OPTION) {
//            List<altaIngredientes> lista = new ArrayList();
//            for (int indice : tblABCExpedientes.getSelectedRows()) {
//                lista.add((altaIngredientes) modelo.getValueAt(indice, 0));
//            }
//            bd.eliminarIngredientes(lista);
//            JOptionPane.showMessageDialog(this, "Ingrediente Eliminado");
//            /*Una vez ejecutado, el método principal, se ejecuta otro método dentro que 
//             también será ejecutado una vez terminado.  
//             */
//            cargarDatosIngredientes();
//        }
//    }
//
//    private void agregarIngrediente() {
//
//        bd.agregarIngrediente(new altaIngredientes(
//                        txtNombreIngrediente.getText(),
//                        Integer.parseInt(txtFecha.getText()),
//                        txtTipoCaso.getText()
//                )
//        );
//        /*      Una vez ejecutado, el método principal, se ejecuta otro método dentro que 
//         también será ejecutado una vez terminado.  
//         */
//        cargarDatosIngredientes();
//
//    }
//
//    private void modificarIngrediente() {
//        bd.modificarIngrediente(new altaIngredientes(
//                idIngredienteModificar,
//                txtNombreIngrediente.getText(),
//                Integer.parseInt(txtFecha.getText()),
//                txtTipoCaso.getText()
//        )
//        );
//        /*Una vez ejecutado, el método principal, se ejecuta otro método dentro que 
//         también será ejecutado una vez terminado.  
//         */
//        cargarDatosIngredientes();
////        System.out.println(idIngredienteModificar);
//    }
}
